### PR TITLE
Update v1.4.1

### PR DESCRIPTION
**Pull request by tongyuantongyu**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Update v1.4.1.

Not sure why, but maybe it's the `{{ name }}` in url that is preventing bot from detecting upstream repo and making automatic PR for new releases. It's unlikely upstream will change its repo name, so just write the name down should be OK.

### CODE REVIEW

**Comment by tongyuantongyu** [comment]
@conda-forge-admin, please rerender

**Comment by tongyuantongyu** [comment]
@traversaro @seanyen Could you take a look at this? Thanks!

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
> @traversaro @seanyen Could you take a look at this? Thanks!

Sure, let's rerender to make sure nothing changed in the last two months. Thanks for handling this, not sure why the autotick bot did not opened a PR here.

**Pull request merged**
